# Configuration pour le comptage entre zones

detector:
  model_path: "models/yolov8n.pt"
  conf_threshold: 0.25
  iou_threshold: 0.45
  device: "auto"
  target_classes: ["person"]

tracker:
  max_disappeared: 30
  min_iou_threshold: 0.3

zone_counting:
  zones:
    zone_a:
      name: "Zone A"
      points: [[50, 50], [200, 50], [200, 200], [50, 200]]  # Coordonnées du polygone
      color: [0, 255, 0]  # Couleur BGR
    
    zone_b:
      name: "Zone B"
      points: [[300, 50], [450, 50], [450, 200], [300, 200]]
      color: [255, 0, 0]
    
    zone_c:
      name: "Zone C"
      points: [[150, 250], [350, 250], [350, 400], [150, 400]]
      color: [0, 0, 255]

# Configuration de sortie
output:
  save_results: true
  results_file: "results/zone_counting_results.json"
